export const REQUEST_EVENTS = 'REQUEST_EVENTS';
export const RECEIVE_EVENTS = 'RECEIVE_EVENTS';

export const REQUEST_INDIVIDUAL_EVENT = 'REQUEST_INDIVIDUAL_EVENT';
export const RECEIVE_INDIVIDUAL_EVENT = 'RECEIVE_INDIVIDUAL_EVENT';

// Messages
export const LOAD_MESSAGES = 'LOAD_MESSAGES';
export const LOAD_MESSAGES_SUCCESS = 'LOAD_MESSAGES_SUCCESS';
export const RECEIVE_MESSAGE = 'RECEIVE_MESSAGE';
