// Events
export const REQUEST_INDIVIDUAL_EVENT = 'REQUEST_INDIVIDUAL_EVENT';
export const RECEIVE_INDIVIDUAL_EVENT = 'RECEIVE_INDIVIDUAL_EVENT';

export const CREATE_EVENT_REQUEST = 'CREATE_EVENT_REQUEST';
export const CREATE_EVENT_RESPONSE = 'CREATE_EVENT_RESPONSE';

export const UPDATE_EVENT_REQUEST = 'UPDATE_EVENT_REQUEST';
export const UPDATE_EVENT_RESPONSE = 'UPDATE_EVENT_RESPONSE';

export const REQUEST_EVENT_MEMBERS = 'REQUEST_EVENT_MEMBERS';
export const RECEIVE_EVENT_MEMBERS = 'RECEIVE_EVENT_MEMBERS';

export const REQUEST_EVENT_INVITES = 'REQUEST_EVENT_INVITES';
export const RECEIVE_EVENT_INVITES = 'RECEIVE_EVENT_INVITES';


// Session, login, logout
export const REQUEST_SESSION = 'REQUEST_LOGIN';
export const RECEIVE_SESSION = 'RECEIVE_SESSION';
export const FAILED_TO_LOGIN = 'FAILED_TO_LOGIN';

export const REQUEST_LOGOUT = 'REQUEST_LOGOUT';
export const DELETE_SESSION = 'DELETE_SESSION';
export const FAILED_TO_LOGOUT = 'FAILED_TO_LOGOUT';

export const REDIRECT_TO_LOGIN = 'REDIRECT_TO_LOGIN';

export const SESSION_STATUS_PENDING = 'SESSION_STATUS_PENDING';
export const SESSION_STATUS_LOGGED_IN = 'SESSION_STATUS_LOGGED_IN';
export const SESSION_STATUS_LOGGED_OUT = 'SESSION_STATUS_LOGGED_OUT';

// Messages
export const ADD_MESSAGE = 'ADD_MESSAGE';
export const LOAD_MESSAGES = 'LOAD_MESSAGES';
export const LOAD_MESSAGES_SUCCESS = 'LOAD_MESSAGES_SUCCESS';
export const RECEIVE_MESSAGE = 'RECEIVE_MESSAGE';

// Sign up
export const SIGNUP_IDLE = 'SIGNUP_IDLE';
export const SIGNUP_REQUEST = 'SIGNUP_REQUEST';
export const SIGNUP_PENDING = 'SIGNUP_PENDING';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAILURE = 'SIGNUP_FAILURE';

// Users
export const REQUEST_USER_EVENTS = 'REQUEST_USER_EVENTS';
export const RECEIVE_USER_EVENTS = 'RECEIVE_USER_EVENTS';

export const REQUEST_USER_INVITES = 'REQUEST_USER_INVITES';
export const RECEIVE_USER_INVITES = 'RECEIVE_USER_INVITES';

export const RECEIVE_DELETE_USER_INVITE = 'RECEIVE_DELETE_USER_INVITE';

export const REQUEST_USER_FROM_EMAIL = 'REQUEST_USER_FROM_EMAIL';
export const RECEIVE_USER_FROM_EMAIL = 'RECEIVE_USER_FROM_EMAIL';
export const RECEIVE_USER_FROM_EMAIL_NOT_FOUND = 'RECEIVE_USER_FROM_EMAIL_NOT_FOUND';

export const USER_TYPING_EMAIL = 'USER_TYPING_EMAIL';
export const USER_ALREADY_PART_OF_THE_EVENT = 'USER_ALREADY_PART_OF_THE_EVENT';
