export const REQUEST_EVENTS = 'REQUEST_EVENTS';
export const RECEIVE_EVENTS = 'RECEIVE_EVENTS';

export const REQUEST_INDIVIDUAL_EVENT = 'REQUEST_INDIVIDUAL_EVENT'
export const RECEIVE_INDIVIDUAL_EVENT = 'RECEIVE_INDIVIDUAL_EVENT'

export const REQUEST_SESSION = 'REQUEST_LOGIN';
export const RECEIVE_SESSION = 'RECEIVE_SESSION';
export const FAILED_TO_LOGIN = 'FAILED_TO_LOGIN';
export const SESSION_STATUS_PENDING = 'SESSION_STATUS_PENDING';
export const SESSION_STATUS_LOGGED_IN = 'SESSION_STATUS_LOGGED_IN';
export const SESSION_STATUS_LOGGED_OUT = 'SESSION_STATUS_LOGGED_OUT';

// Messages
export const ADD_MESSAGE = 'ADD_MESSAGE';
export const LOAD_MESSAGES = 'LOAD_MESSAGES';
export const LOAD_MESSAGES_SUCCESS = 'LOAD_MESSAGES_SUCCESS';
export const RECEIVE_MESSAGE = 'RECEIVE_MESSAGE';

// Sign up
export const SIGNUP_IDLE = 'SIGNUP_IDLE';
export const SIGNUP_REQUEST = 'SIGNUP_REQUEST';
export const SIGNUP_PENDING = 'SIGNUP_PENDING';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAILURE = 'SIGNUP_FAILURE';
